### PR TITLE
33 check arguments

### LINKED ISSUE #33: If topic is empty, program segfaults
When trying to consume the last 10 messages from an empty topic the program segfaults with no output. A warning/error as well as a return code should be added or perhaps an exception thrown to indicate that there are no messages on the topic or that the user has requested too many messages to consume from.

command: `bin/kafkacow -C -b localhost -t TEST_events -o 10`

output: 

```
[2018-09-24 11:22:17.882] [LOG] [info] Welcome to spdlog!
Segmentation fault (core dumped)
```

Also, when the argument is given a negative number the same behaviour occurs. This can be fixed by adding a check to the CLI11 option.

### PR DESCRIPTION
**Pull request by mchorazak**
### Description of work

CLI check() method ensures that parameters -o and -g are not negative.

RequestHandler verifies if value is correct(e.g. if given offset exists).

### Issue

Closes #33 

### Acceptance Criteria
main.cpp lines 16-20, 24-27
RequestHandler::verifyNLast
RequestHandler::verifyOffset

### Unit Tests

Tests added to cover requesthandler verification methods.

---

## Code Review (To be filled in by the reviewer only)

- [ ] Is the code of an acceptable quality?
- [ ] Do the changes function as described and is it robust?

---

## Nominate for Group Code Review (Anyone can nominate it)
Indicate if you think the code should be reviewed in a Thursday code review session.

- [ ] Recommend for group code review

Also, nominate it on the code_review Slack channel (does someone want to automate this?).

### CODE REVIEW

File: src/RequestHandler.cpp [hunk 1]
```diff
@@ -76,6 +78,25 @@ void RequestHandler::subscribeConsumeAtOffset(std::string TopicName,
   }
 }
 
+/// Ensures there are messages to read at offset provided by the user, otherwise
+/// throws an ArgumentsException.
+///
+/// \param Offset
+/// \param TopicName
+void RequestHandler::verifyOffset(int32_t Offset, std::string TopicName) {
```
Comment (rerpha) [inline src/RequestHandler.cpp]: Both arguments can be const-ref here eg: 
`const int32_t Offset, const std::string TopicName`

this looks like it can also be applied to `verifyNLast` as well

File: src/ConnectKafka.cpp [hunk 2]
```diff
@@ -200,7 +200,7 @@ void ConnectKafka::subscribeToLastNMessages(int64_t NMessages,
       getTopicsHighAndLowOffsets(Topic);
 
   // get highest offset of all partitions
-  int64_t HighestOffest = 0;
+  int32_t HighestOffest = 0;
```
Comment (rerpha) [inline src/ConnectKafka.cpp]: typo in offset
