### PR TITLE
Error handling

### LINKED ISSUE #47: Fix ErrStr in ConnectKafka config

### LINKED ISSUE #48: Handle exceptions closer to where they are thrown

### PR DESCRIPTION
**Pull request by mchorazak**
### Description of work

Exceptions are now handled closer to where they are thrown.
Changed strange ErrStr usage.
Deleted unnecessary configuration property.

### Issue

Closes #47 
Closes #48 

### Acceptance Criteria

ConnectKafka.cpp
main.cpp

### Unit Tests

n/a

---

## Code Review (To be filled in by the reviewer only)

- [ ] Is the code of an acceptable quality?
- [ ] Do the changes function as described and is it robust?

---

## Nominate for Group Code Review (Anyone can nominate it)
Indicate if you think the code should be reviewed in a Thursday code review session.

- [ ] Recommend for group code review

Also, nominate it on the code_review Slack channel (does someone want to automate this?).

### CODE REVIEW

File: src/ConnectKafka.cpp [hunk 1]
```diff
@@ -3,22 +3,39 @@
...
+}
+
 std::unique_ptr<RdKafka::Conf>
 createGlobalConfiguration(const std::string &BrokerAddr) {
   auto conf = std::unique_ptr<RdKafka::Conf>(
       RdKafka::Conf::create(RdKafka::Conf::CONF_GLOBAL));
   std::string ErrStr;
+  std::shared_ptr<spdlog::logger> Logger = spdlog::get("LOG");
   conf->set("metadata.broker.list", BrokerAddr, ErrStr);
+  logError(ErrStr, Logger);
```
Comment (matthew-d-jones) [inline src/ConnectKafka.cpp]: Lots of repetition, this is a sign that this should be refactored into a separate function.

File: src/ConnectKafka.cpp [hunk 2]
```diff
@@ -30,17 +47,25 @@ std::unique_ptr<RdKafka::Metadata> ConnectKafka::queryMetadata() {
   RdKafka::Metadata *metadataRawPtr(nullptr);
   Consumer->metadata(true, nullptr, &metadataRawPtr, 1000);
   std::unique_ptr<RdKafka::Metadata> metadata(metadataRawPtr);
-  if (!metadata) {
-    throw std::runtime_error("Failed to query metadata from broker");
+  try {
+    if (!metadata) {
+      throw std::runtime_error("Failed to query metadata from broker");
+    }
+  } catch (std::runtime_error &E) {
```
Comment (matthew-d-jones) [inline src/ConnectKafka.cpp]: You're not doing anything different with `runtime_error` to any other `exception`, so there is no point having the `catch (std::runtime_error &E)`

File: src/ConnectKafka.cpp [hunk 3]
```diff
@@ -30,17 +47,25 @@ std::unique_ptr<RdKafka::Metadata> ConnectKafka::queryMetadata() {
...
 
-ConnectKafka::ConnectKafka(std::string Broker, std::string ErrStr)
-    : Logger(spdlog::get("LOG")) {
+ConnectKafka::ConnectKafka(std::string Broker) : Logger(spdlog::get("LOG")) {
+  std::string ErrStr;
   this->Consumer =
       std::shared_ptr<RdKafka::KafkaConsumer>(RdKafka::KafkaConsumer::create(
           createGlobalConfiguration(Broker).get(), ErrStr));
+  if (!ErrStr.empty())
+    Logger->error(ErrStr);
```
Comment (matthew-d-jones) [inline src/ConnectKafka.cpp]: It would be good to add something to the logged error to say where this error occurred ("Error creating Kafka Consumer in ConnectKafka...").

File: src/ConnectKafka.cpp [hunk 4]
```diff
@@ -65,38 +90,45 @@ KafkaMessageMetadataStruct ConnectKafka::consumeFromOffset() {
...
-  case RdKafka::ERR_NO_ERROR:
-    // Real message
-    if (KafkaMsg->len() > 0) {
-      std::string Payload(static_cast<const char *>(KafkaMsg->payload()),
-                          static_cast<int>(KafkaMsg->len()));
-      DataToReturn.Payload = Payload;
-      DataToReturn.Partition = KafkaMsg->partition();
-      DataToReturn.Offset = KafkaMsg->offset();
-      DataToReturn.Timestamp = KafkaMsg->timestamp().timestamp;
+  try {
```
Comment (matthew-d-jones) [inline src/ConnectKafka.cpp]: I don't think this `try-catch` block is necessary, you are already handling the errors from `rdkafka` there shoudn't be an exception thrown.

File: src/main.cpp [hunk 5]
```diff
@@ -45,21 +45,20 @@ int main(int argc, char **argv) {
...
-  auto KafkaConnection = std::make_unique<ConnectKafka>(Broker, ErrStr);
 
+  auto KafkaConnection = std::make_unique<ConnectKafka>(Broker);
   RequestHandler NewRequestHandler(std::move(KafkaConnection), UserArguments);
   try {
     NewRequestHandler.checkAndRun();
   } catch (ArgumentsException &E) {
-    std::cout << E.what() << std::endl;
+    Logger->error(E.what());
+  } catch (std::runtime_error &E) {
```
Comment (matthew-d-jones) [inline src/main.cpp]: Same as earlier, `std::runtime_error` would also be caught by `catch (std::exception &E)` and you aren't handling them any differently.
